# Generated by Django 4.0.2 on 2022-07-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField()),
                ('strike_price', models.IntegerField()),
                ('ticker', models.CharField(blank=True, max_length=50, null=True)),
                ('calls_oi', models.IntegerField()),
                ('calls_change_oi', models.IntegerField()),
                ('calls_iv', models.FloatField()),
                ('calls_ltp', models.FloatField()),
                ('calls_volume', models.IntegerField()),
                ('calls_buy_qty', models.IntegerField()),
                ('calls_sell_qty', models.IntegerField()),
                ('puts_oi', models.IntegerField()),
                ('puts_change_oi', models.IntegerField()),
                ('puts_iv', models.FloatField()),
                ('puts_ltp', models.FloatField()),
                ('puts_volume', models.IntegerField()),
                ('puts_buy_qty', models.IntegerField()),
                ('puts_sell_qty', models.IntegerField()),
                ('spot', models.FloatField()),
                ('created_on', models.DateTimeField()),
            ],
        ),
        migrations.AddIndex(
            model_name='chain',
            index=models.Index(fields=['ticker', 'created_on'], name='options_cha_ticker_2cf2d7_idx'),
        ),
    ]
