#from research.strategies.double_top_break_strategy import DoubleTopBreakStrategy
#from research.strategies.state_cap_strategy import StateCapStrategy
#from research.strategies.opening_trend_bearish import OpeningBearishTrendStrategy
from live_algo.friday.friday_candle_first_30_mins import FridayCandleFirst30Buy,FridayCandleFirst30Sell #, #FridayCandleBuyFullDay
from research.strategies.multi_pattern_q_strategy import MultiPatternQueueStrategy
from research.technical_strategies.price_below_ema import PriceBreakEMADownward
from research.technical_strategies.price_reverse_ema_down import PriceReverseBreakDownEMA
