# Generated by Django 4.0.2 on 2022-07-21 06:39

from django.db import migrations, models
import django.utils.timezone
import website.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True, verbose_name='Phone Number')),
                ('username', models.CharField(blank=True, max_length=500, null=True, verbose_name='Username')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user_type', models.CharField(blank=True, choices=[('U1', 'Paid User'), ('U2', 'Test User')], max_length=200, null=True)),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', website.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('order_time', models.DateTimeField()),
                ('strat_id', models.CharField(max_length=20)),
                ('signal_id', models.CharField(max_length=20)),
                ('trigger_id', models.IntegerField(blank=True, null=True)),
                ('order_type', models.CharField(max_length=10)),
                ('symbol', models.CharField(max_length=50)),
                ('side', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('product', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPasswords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_lock', models.BooleanField(default=False)),
                ('last_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user_password',
            },
        ),
        migrations.AddIndex(
            model_name='trades',
            index=models.Index(fields=['order_date'], name='website_tra_order_d_26ac2e_idx'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
